apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "api-v2.fullname" . }}
  labels:
    {{- include "api-v2.labels" . | nindent 4 }}
spec:
#{{- toYaml .Values.env | nindent 2 }}